# Generated by Django 3.0.8 on 2022-11-13 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.CustomUser')),
            ],
        ),
    ]
