# Generated by Django 3.0.8 on 2022-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_leagueaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueaccount',
            name='region',
            field=models.TextField(default='EUNE'),
        ),
    ]
